version: '2'
services:
  db:
    image: mysql:5.5
    volumes:
      - swachalit-mysql:/var/lib/mysql
    env_file:
      - .env.mysql
  app:
    build: .
    depends_on:
      - db
    command: script/run_docker_app.sh
    volumes:
      - .:/app
    ports:
      - "8800:8800"
    env_file:
      - .env
volumes:
  swachalit-mysql:



